%read dat files generated by the brookhaven correlator
% The first 37 entries are parameters
% from the experiment.
% Entry 7 is the number of data channels
% entry 21 is the number of extended baseline
% channels. The sum of these should
% add to the number of rows of data

% the program gives you two 1_d arrays: time (in microseconds)and cor
% which you can then use in the fitting program
% that you write.

clear all; clf

h=fopen('153um_DI.dat');     %put your file name in here


f=fscanf(h,'%f');

fclose(h);
dat_length=f(7)+f(21);

dat=f(38:38+2*dat_length-1);

time=dat(1:2:2*dat_length-1);
cor=dat(2:2:2*dat_length);

baseline=mean(cor(dat_length-7:dat_length));
cor=cor/baseline-1;
semilogx((time),cor,'*')
Data = [cor time];

csvwrite('153um_DI.txt',Data)

